include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .dart_tool/**
    - build/**
    - android/**
    - ios/**
    - linux/**
    - macos/**
    - windows/**
    - web/**

linter:
  rules:
    # Relax a few chatty lints while scaffolding
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
