name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: flutter pub get
        run: flutter pub get

      # Format but don't fail the build if it changes files
      - name: dart format
        run: dart format --output=none .

      - name: dart analyze
        run: dart analyze lib
